-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.campaigns
(
    cf_id serial NOT NULL,
    contact_id integer NOT NULL,
    company_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    goal numeric NOT NULL,
    pledged numeric NOT NULL,
    outcome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    backers_count integer NOT NULL,
    country character varying(255) COLLATE pg_catalog."default" NOT NULL,
    currency character varying(50) COLLATE pg_catalog."default" NOT NULL,
    launch_date date NOT NULL,
    end_date date NOT NULL,
    category_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    subcategory_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT campaigns_pkey PRIMARY KEY (cf_id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    category_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    category_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id integer NOT NULL,
    first_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT contacts_pkey PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public.subcategories
(
    subcategory_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    subcategory character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT subcategories_pkey PRIMARY KEY (subcategory_id)
);
END;